# Generated by Django 5.2.1 on 2025-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_customuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userclient",
            old_name="first_name",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="userclient",
            old_name="username",
            new_name="storename",
        ),
        migrations.RemoveField(
            model_name="userclient",
            name="last_name",
        ),
        migrations.AddField(
            model_name="userclient",
            name="client_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userclient",
            name="consumer_key",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="userclient",
            name="consumer_secret",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.DeleteModel(
            name="Token",
        ),
    ]
