# Generated by Django 5.2.1 on 2025-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_first_name_userclient_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclient",
            name="user_client_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
