# Generated by Django 5.2.1 on 2025-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userclient_user_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclient",
            name="user_client_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
