# Generated by Django 5.2.1 on 2025-07-07 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userclient_user_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclient",
            name="user_client_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
