# Generated by Django 5.2.1 on 2025-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="expense_category_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentoption",
            name="payment_option_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
