# Generated by Django 5.2.8 on 2025-12-04 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_customer_customer_id_alter_expense_expense_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_channels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AnonymousProfile',
            fields=[
                ('anonymous_customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('features_json', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
