# Generated by Django 5.2.8 on 2025-12-04 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_grnheader_grndetail_purchaseorderheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnheader',
            name='purchase_header',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_headers', to='purchases.purchaseheader'),
        ),
    ]
