# Generated by Django 5.2.8 on 2025-12-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_remove_grnheader_po_header_grnheader_purchase_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnheader',
            name='po_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_grn_headers', to='purchases.purchaseorderheader'),
        ),
    ]
