# Generated by Django 5.2.8 on 2025-12-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_grnheader_po_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnheader',
            name='purchase_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_headers', to='purchases.purchaseheader'),
        ),
    ]
