# Generated by Django 5.2.8 on 2025-12-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchaseorderheader_converted_purchase'),
        ('purchases', '0009_alter_grnheader_purchase_header'),
    ]

    operations = [
    ]
