# Generated by Django 5.1.7 on 2025-04-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesDetail",
            fields=[
                (
                    "sales_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesHeader",
            fields=[
                (
                    "sales_header_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("order_number", models.CharField(max_length=255, unique=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("receipt_id", models.AutoField(primary_key=True, serialize=False)),
                ("receipt_number", models.CharField(max_length=255, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("narration", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.customer",
                    ),
                ),
                (
                    "payment_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.paymentoption",
                    ),
                ),
            ],
        ),
    ]
