# Generated by Django 5.2.1 on 2025-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salesdetail",
            name="sales_detail_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salesheader",
            name="sales_header_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
