# Generated by Django 5.2.1 on 2025-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_salesheader_status_salesreservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreservation",
            name="expiry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
