# Generated by Django 5.2.8 on 2025-12-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_customer_consent_timestamp_and_more'),
        ('sales', '0009_salesreservation_expiry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='anonymous_customer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='card_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='credit_account_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='mpesa_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile Money'), ('CREDIT', 'Store Credit'), ('OTHER', 'Other')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='anonymous_customer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='card_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='credit_account_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='mpesa_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile Money'), ('CREDIT', 'Store Credit'), ('OTHER', 'Other')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.customer'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.customer'),
        ),
    ]
