# Generated by Django 5.2.8 on 2025-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_receipt_anonymous_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='link_token',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
