# Generated by Django 5.2.1 on 2025-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_location_stocktransfer_productlocationstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
