# Generated by Django 5.2.1 on 2025-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_average_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
